### ISSUE TITLE
Document custom LLVM optimization passes

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#1018]
Please post the results of running the novel LLVM optimization passes on our example contracts in this issue. Also, please document the steps we need to take to reproduce these results here. This will be really helpful for us when deciding which optimization issues to tackle next.

The examples can be found in the `examples` folder of this repository. Note that the `examples/delegator` has multiple contracts in it, [the readme](https://github.com/paritytech/ink/tree/master/examples/delegator#delegator-smart-contract) lists the four contracts.

Please use the examples from the ink! `master` branch for your evaluation, we haven't released all optimizations yet.

For the comparison it's important that the contracts are build with `cargo-contract` in its latest version (currently `0.15.0`). This is because we already do a number of optimizations there. You can install the latest version via `cargo install cargo-contract --force --locked`.

A dependency of the tool is `wasm-opt`, you can download a binary directly from [here](https://github.com/WebAssembly/binaryen/releases/tag/version_101). The version should be at least 101, you can query your local version via `wasm-opt --version`.

For building the individual examples you should use
```
cargo +nightly contract build \
  --release \
  --output-json \
  --manifest-path=/home/michi/projects/ink/examples/flipper/Cargo.toml | \
jq .optimization_result.optimized_size
```
The `--release` is really important, this way the contracts won't contain any debugging logic. The printed number is the final optimized size in kb, this is the number we are looking for.

**Comment by jamesblacklock** [comment]
My earlier estimate for compiling the erc20 contract was that the FunctionMerging (HyFM) pass would reduce code size by about 6%. However, when trying to replicate this data (and also incorporate function outlining, per https://github.com/paritytech/ink/issues/1022) I encountered numerous issues relating to rustc & LLVM changes that broke my branches.

I have spent too much time trying to get this stuff to work again and I am going to put this on the back burner in order to help Dmitry with more important stuff (unless, of course, I am informed that this should be the highest priority).
