### ISSUE TITLE
mulitsig example contract: can not call `add_owner`, `remove_owner`, `replace_owner`

### ISSUE THREAD

**Issue by achimcc** [paritytech/ink#1178]
Whenever I try to invoke any of the functions `add_owner`, `remove_owner`, `replace_owner` of the `multisig` ink! contract from the examples folder, I receive the following error:

> ERROR: Module error: Contracts: ContractTrapped
> 
> Contract trapped during execution.

I did test it with apps, contracts ui and cargo-contract with:

cargo-contract 0.17.0-c6f9de0-x86_64-linux-gnu
ink! 3.0.0-rc9
substrate-contracts-node 0.8.0-382b446-x86_64-linux-gnu

Also not successfull with canvas on rococco.

I also checked that they are currently not tested by ink! waterfall, I'd suggest to add tests for them.

**Comment by agryaznov** [comment]
Well, as a multisig's own essense dictates, this method should be invoked not by a single user account but rather by the multisig contract itself!
For that, one of the contract owners should use `submit_transaction()` for submitting the tx which should call `add_owner()`, then it should get enough confirmations from the multisig wallet owners by `confirm_transaction()`, and only after that in could get invoked by `invoke_transaction()`.

Wow! It may seem a lil bit tricky, but feel free to look at the contract [docs](https://github.com/paritytech/ink/blob/master/examples/multisig/lib.rs#L299) which hepls to get into it by the example.  

---

Anyway, this contract had a problem indeed, but in a different aspect: it should had have calling flags being setup to allow re-entrancy for that tricky methods which call the contract's own message. Otherwise, it fails (fairly enough) with a `contracts:ReentranceDenied`. This is to be fixed by the upcoming PR.
