### ISSUE TITLE
Contract Development Scaffold

### ISSUE THREAD

**Issue by HCastano** [paritytech/ink#1330]
It would be nice to see something like [Scaffold-ETH](https://github.com/scaffold-eth/scaffold-eth) but for ink!. The motivation here would be to get builders up and running with an entire application template quickly.

For us this would include:
- Basic example ink! contract
- Substrate node template + Contracts pallet
- Barebones UI which is using Polkadot JS Apps (or CAPI once that's ready)

Here are some other templates that might be interesting to reference:
- https://github.com/paulrberg/hardhat-template
- https://github.com/InterWasm/cw-template

**Comment by TomaszWaszczyk** [comment]
> Barebones UI which is using Polkadot JS Apps (or CAPI once that's ready)

Does it make sense that as a UI to Scaffold Ink repository I will use [the repository](https://github.com/paritytech/contracts-ui)? If not, please let me know which one, if possible.

**Comment by codespool** [comment]
We're developing just that over at Astar:
https://github.com/AstarNetwork/swanky-cli
It is missing the UI right now, but it will be a part of v1 release mid November.
You get a node, flipper and psp22 contract templates out of the box. Can manage users, compile and deploy the contract.
More features to come.

**Comment by wottpal** [comment]
gm 🌻

I just started building something like this under https://github.com/scio-labs/inkathon (https://inkathon.xyz)! 

I've already built a pretty sophisticated boilerplate for the eth/evm-ecosystem (https://github.com/scio-labs/ethathon) and wanted to translate this to the substrate-/polkadotjs-/ink-world. It's still super early & work-in-progress, but basic contract deploy & read/write interactions are already working. 

Just to be clear, this is not meant for everyone as the stack is somewhat opinionated (tailwindcss, nextjs, ...). But still, it's a great starting point not only for small hackathon projects as everything is set up nicely, because IMO it can also become a great starter kit for more production-oriented projects with more collaborators (husky, eslint, prettier, lint-stages – all is configured properly).

Please let me know your feedback and feel free to open issues in the respective repositories.
