### ISSUE TITLE
Define a Standard for Proxy Storage Variables

### ISSUE THREAD

**Issue by HCastano** [paritytech/ink#1680]
In the Ethereum world there is [EIP-1967](https://eips.ethereum.org/EIPS/eip-1967) which defines a well-known set of storage
slots used to represent key variables in the Proxy pattern, such as the `admin` and
`implementation`.

It would be nice to have something similar for ink!.

The EIP-1967 approach uses storage slots that are known to not be used by the Solidity
compiler. I don't think we can make the same guarantees with `pallet-contracts` or
Substrate, so we'll probably need to find a different approach to this.

**Comment by xermicus** [comment]
I have a very strong opinion on this. Please use the exact storage slots as defined in `EIP-1967`. From a technical standpoint, it doesn't really matter. However, if this will be different with `ink!`, it opens a perfect footgun regarding compatibility with Solidity contracts. If we use different values, we must yell at everyone using Solang (or aks!) that by the way, this is different on Polkadot (for no apparent reason?). People _will_ inevitably just use existing Solidity code, getting caught off-guard by this. _ Unless_ we first hand to decide to stick to those storage slots and call it a day.

**Comment by SkymanOne** [comment]
AFAIK we are using a different hash function across ink! (blake2x256). Secondly, using storage slots implies using `Lazy` with `ManualKey` in a proxy contract which adds some overhead, and since we don't have a problem with storage collision as in solidity, developers can just define those in a packed layoutful storage. 

If we have a strong requirement to have matching storage slots with solidity, we can surely propose a PSP
with a fields like `implementation: Lazy<AccountId, ManualKey< 0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc >>`

**Comment by xermicus** [comment]
> AFAIK we are using a different hash function across ink! (blake2x256).

How does the this matter? The pre-image for the storage slots in EIP-1967 isn't known anyways (on purpose).

>  Secondly, using storage slots implies using Lazy with ManualKey in a proxy contract which adds some overhead, and since we don't have a problem with storage collision as in solidity, developers can just define those in a packed layoutful storage.

ink! contracts do potentially have storage collisions when using `delegatecall`? EIP-1967 just defines address slots and asks the compiler to not allocate them (at least knowingly, as per convention). Reading them is fine (the ref. impl. in the EIP does it).

> If we have a strong requirement to have matching storage slots with solidity

Technically, I don't see a strong requirement for picking any particular slot. And given that, picking different ones would just set us up for bad interop with Solidity.

**Comment by SkymanOne** [comment]
> How does the this matter (also, both are 32 bytes)? The pre-image for the storage slots in EIP-1967 isn't known anyways (on purpose).

The hash is derived by running the hash function on the known preimage and then subtracting 1. We can either take hash from EIP directly or derive our own using blake2x256.

> EIP-1967 just defines address slots and asks the compiler to not allocate them

We don't have a compiler. We can achieve this only using lints.

If we get to hard-code those slots into ink! storage somehow, that would imply that every new contract would be deployed with these 3 empty proxy slots that are also wrapped into `Lazy` (since it is the only way to specify a key). `Lazy` automatically adds some processing overhead. So we are ultimately forcing devs to use `Lazy` for proxy fields. Do we want this?

**Comment by xermicus** [comment]
> So we are ultimately forcing devs to use Lazy for proxy fields. Do we want this?

Ultimately, you can't force anyone to store anything specific in any storage slot. At least not on the contract source level. But if you define a standard, yes you are asking contract devs to adhere to that. And for upgradable contracts and proxy implementations, _not_ using all manual keys [is a bad idea](https://github.com/paritytech/ink/issues/1825) anyways isn't it?

**Comment by ascjones** [comment]
I assume we are discussing the following section of the OZ report https://blog.openzeppelin.com/security-review-ink-cargo-contract

![image](https://github.com/paritytech/ink/assets/75586/122ca461-4509-4126-b655-25d63d9445e8)

My initial thought is that this (predefined storage slots for proxy storage) is not something that should be baked into the language itself, and that such standards are defined and adopted "organically", e.g. with the existing PSP standards from openbrush.

Further, the Rationale for https://eips.ethereum.org/EIPS/eip-1967 states that:

> The rationale for this is that proxies should never expose functions to end users that could potentially clash with those of the logic contract.

We now have built in protection against selector clashing attacks: https://github.com/paritytech/ink/pull/1708 so this is not an issue, the public fallback function can be called directly to force the upgrade.

> They are chosen in such a way so they are guaranteed to not clash with state variables allocated by the compiler, since they depend on the hash of a string that does not start with a storage index

A less opinionated way to do it, to allow standards to be developed, would be to similarly define a range of storage keys we guarantee will never be written to  by the derived `Storable` implementations. I don't know how feasible/practical this is.

### set_code_hash

Ideally we would promote the usage of `set_code_hash` as the preferred mechanism for implementing the basic "proxy" pattern. It is something that already exists and would allow the implementation of `cargo contract upgrade` with a pattern such as https://github.com/paritytech/ink/pull/1909. The `upgrade` command could look for common message names such as `migrate` or `set_code_hash` on the contracts and execute those.

**Comment by cmichi** [comment]
The upgrade command could look for common message names such as `migrate` or `set_code_hash` on the contracts and execute those.

I think, best would be to have the `cargo contract upgrade` command ask which message to execute. Otherwise it'll always be a heuristic. Could be used to suggest possible message names though, in case none is provided.

**Comment by xgreenx** [comment]
> My initial thought is that this (predefined storage slots for proxy storage) is not something that should be baked into the language itself, and that such standards are defined and adopted "organically", e.g. with the existing PSP standards from openbrush.

I agree. The implementer of the Proxy contract is responsible for using a separate storage cell to avoid overlapping. As an example, OpenBrush already uses a [separate storage cell](https://github.com/Brushfam/openbrush-contracts/blob/3.2.0/contracts/src/upgradeability/proxy/mod.rs#L47).

> A less opinionated way to do it, to allow standards to be developed, would be to similarly define a range of storage keys we guarantee will never be written to by the derived Storable implementations. I don't know how feasible/practical this is.

I don't think it is possible to implement because any public API provided by ink! can invalidate/corrupt the storage. ink! generates code that works with the storage on the user's side, so it uses a public API. Anyone can easily reuse these public functions in `Storable` implementation.

Plus, the safest way is to control it during runtime -> it affects the performance.

> The upgrade command could look for common message names such as migrate or set_code_hash on the contracts and execute those.

Usually, this kind of functionality is hidden or uses other names, but yeah, we can ask users to use pre-defined names. But it already sounds like some standardization=)

Maybe we can have `cargo contract upgrade` or `cargo contract migrate` commands that receive `old_contract.metadata` and `new_contract.metadata` compare them and check for storage layout conflicts?

The problem with this solution is that it will not work in the case of the Diamond standard. But we can have one command for storage migration(between two contracts) and another like `cargo contract check-conflicts` that works with multiple files and scans for overlapping.

**Comment by ascjones** [comment]
> Usually, this kind of functionality is hidden or uses other names, but yeah, we can ask users to use pre-defined names. But it already sounds like some standardization=)

Agreed, then we can simply require some arguments e.g. `--init-migration-message` and `--perform-migration-message`

**Comment by SkymanOne** [comment]
Overall, I agree that `set_code_hash` should be our "standardized" way of upgradeability. However, before we move on to `cargo contract upgrade` I think we need to develop necessary API for the migration in case there are amendments to the storage layout - #1388 

> A less opinionated way to do it, to allow standards to be developed, would be to similarly define a range of storage keys we guarantee will never be written to by the derived Storable implementations. I don't know how feasible/practical this is.

I still believe we need to address this point for future purposes. Perhaps reserve some chunk of keys for "system" purposes, have some range of keys which are never automatically allocated.

**Comment by ascjones** [comment]
`pallet-contracts` already has a built-in mechanism for contract upgradeability via `set_code_hash`. This already satisfies many of the requirements of EIP-1967: 
 - protection from being overwritten by contract upgrades
 - standard "interface" for block explorers to keep track of contract upgrades, see the [`ContractCodeUpdated](https://github.com/paritytech/polkadot-sdk/blob/c879d1d5827f1fa4f72621ce185fa08ac3ea8d31/substrate/frame/contracts/src/lib.rs#L908)` event.

It is possible that such a standard could still be proposed/developed and adopted, As @xgreenx mentioned there is something like this in [`OpenBrush`](https://github.com/Brushfam/openbrush-contracts/blob/3.2.0/contracts/src/upgradeability/proxy/mod.rs#L47).

But this should not be baked into the language itself, given that we have the built-in upgradeability mechanism already which achieves most of what we want.
