### ISSUE TITLE
Allow iteration over Mapping in smart contract

### ISSUE THREAD

**Issue by TomaszWaszczyk** [paritytech/ink#1798]
**Proposal**

It would be helpful to allow making iteration over `Mapping` like it is in any `HashMap`.

**Comment by DamianStraszak** [comment]
Disclaimer: I'm not a member of the ink! team, or parity. Big fan of ink! though :)

I see good reasons why this should NOT be added:
1) There is no way to add it to `Mapping` without a significant overhead, i.e., one would need to add additional storage items to make iteration possible, at the very least. This would also make it not backwards compatible, so pretty much a disaster. 
2) Given the above, one option would be to create a new `MappingWithIteration` which I guess could be done, but I think this is a bad idea as well:
a) It's possible to implement such a  `MappingWithIteration` using `Mapping` as a black box, so better to include it in a helper library, such as OB, instead of ink!, which is supposed to be as simple, and as pure as possible.
b) Such a mapping would be significantly more expensive than regular `Mapping` (the implementation I have in mind would make every operation cost 2-3 storage read/writes), but it giving additional functionality would still lure some users to use it over `Mapping`.

On top of the above, one has to ask the crucial question: what would be a legit use case of a Mapping with iteration in a smart contract? When working with collections in contracts I can distinguish two cases:
1) either you have a smallish, bounded size collection (10-20 elements), then you should keep it in a `Vec<_>` in the main, non-lazy storage. Then you can iterate whenever you want.
2) you have a big, unbounded collection that you keep in a `Mapping`. In such a case, why would you iterate over it? If you do, your contract is probably wrong, because you might hit the gas limit, or some such problem. Each call in a smart contract should have strict bounds on how much gas does it use. And if you iterate over an arbitrarily big collection, then obviously there is a problem with that. 

So I think that allowing users to iterate over `Mapping` might actually be harmful, and lead to them writing bad contracts. That might be a bit extreme, but still...

The only legitimate use case I can see of iterating over Mapping is maybe writing some multi-block migrations of contracts. But I guess even for this, there are other ways to achieve this...

**Comment by SkymanOne** [comment]
It is considered a bad practice to iterate over `Mapping` in a contract. Due to its layoutless nature, the list of keys and values are not available. Adding this functionality will indeed add some overhead to ink! (as mentioned by @DamianStraszak) and may potentially overflow the static buffer. Therefore, it is advised to either keep the list of keys in the `Vec` or somewhere in the frontend and iterate over the values by retrieving individual values from the `Mapping`.

Overall, I am closing the issue as it is not planned to be implemented.

**Comment by TomaszWaszczyk** [comment]
> It is considered a bad practice to iterate over `Mapping` in a contract. Due to its layoutless nature, the list of keys and values are not available. Adding this functionality will indeed add some overhead to ink! (as mentioned by @DamianStraszak) and may potentially overflow the static buffer. Therefore, it is advised to either keep the list of keys in the `Vec` or somewhere in the frontend and iterate over the values by retrieving individual values from the `Mapping`.
> 
> Overall, I am closing the issue as it is not planned to be implemented.

In retrospect, I have come to understand that the idea was not a good one.

**Comment by xgreenx** [comment]
It should be possible to iterate without huge overhead=) https://github.com/paritytech/substrate/issues/11410
But yeah, it is not the best idea=D

**Comment by TomaszWaszczyk** [comment]
> It should be possible to iterate without huge overhead=) [paritytech/substrate#11410](https://github.com/paritytech/substrate/issues/11410) But yeah, it is not the best idea=D

While the iteration could be a potential challenge/footgun for newbies, those who understand its purpose may see it as a pathway to optimization. The outcome depends on the design decisions within ink!, which should be well-documented.., including the possibility of required components.
