### ISSUE TITLE
Add metadata section for errors to add debug information

### ISSUE THREAD

**Issue by riusricardo** [paritytech/ink#210]
It becomes much easier to debug and work with the contract if we can handle text errors for tests.
The issue appears when I try to build the ABI. 
Is there a way during the ABI building process to handle the Result type with strings?
```
Result<(), &'static str>
```
```
error: invalid or unsupported type
```
https://github.com/paritytech/ink/pull/201 I switched to an unsigned integer to handle the return error but it is not as clear as it could be.

**Comment by Robbepop** [comment]
This should kind of work already, however, we do not want to follow the approach of having error strings because this is generally an anti-pattern in the Rust ecosystem for error handling.

What we want to have instead are lightweight error enum values (C-style enums) that are associated with some error strings on the metadata level of a contract. So this task is basically an `ink_abi` + `ink_lang` task since we need support on both sides to make this happen.

**Comment by SkymanOne** [comment]
Closing issue as we have all messages are now wrapped with `Result` and return `LangError`
