### ISSUE TITLE
Using hash functions like sha256

### ISSUE THREAD

**Issue by kigawas** [paritytech/ink#251]
In solidity we can use keccak256, sha256 and ripemd160 and bitcoin script also supports the last two. I only saw keccak256 [here](https://github.com/paritytech/ink/blob/master/utils/src/hash.rs#L81).

If we can officially support sha256 (and ripemd160), it'll be easier to interact with bitcoin and ethereum. Or I can try using `tiny_keccak` with `[u8; 32]`, but it seems not idiomatic since the built-in `Hash` type is better here

**Comment by Robbepop** [comment]
We have not yet figured out a proper API for computing hashes. The biggest problem we have to solve for that is dynamic linking of Wasm binaries since computing hashes is generally compute intense and thus wastes lots of gas if we cannot outsource it somehow to make it waste less gas.

**Comment by kigawas** [comment]
@Robbepop 
Say I'm running a private blockchain (like `substrate --dev`), do I still need to care about gas (or more fundamental, evaluating and differentiating computations' value)?

And I'm not sure whether it's easy for me to use some 3rd party library like `tiny_keccak` to compute sha256 and how it'll influence calculating gas

**Comment by Robbepop** [comment]
A `--dev` chain is pretty much comparable to a real chain if you are looking at economics. So if your contract is not economic in a `--dev` chain it also isn't going to be in a production chain. However, note that gas costs are not yet final. Also we might change certain contract economics in the future. Smart contract economy is a bit more difficult to establish than in the old Ethereum times because of the additional contract storage fees that you have to deal with.

Computing hashes is mostly compute intense. This is why there are some builtins for crypto hashes in Ethereum; to make them less costly and also provide a more efficient underlying implementation than interpreting like the rest of the contract. In Substrate we probably want to di similar things, however, we have not yet figured out a proper scheme for that.

**Comment by WaqarTabish2807** [comment]
How to dynamically generate a hash code for an uploaded file name, and then store it on the blockchain and revert when the user enters the correct hash
