### ISSUE TITLE
Make the currently used EnvTypes impl available

### ISSUE THREAD

**Issue by athei** [paritytech/ink#330]
Sometimes a contract developer needs to name the type of the currently used `EnvTypes` implementation. To prevent hacks like type aliases we should make it easily discoverable. 

This is not working:
`<Self as ink_lang::Env>::EnvAccess`

``the trait ink_lang::env_access::Envis not implemented for multisig_plain::__ink_private::__ink_storage::Storage``

Currently, the `contract!` macro generates a type alias named `EnvTypes` that can be used. However, I think that this is not official. If it should be it must be documented somewhere.

**Comment by Robbepop** [comment]
I think we can close this since this already exists as `EnvTypes`. So we basically need to better communicate this if we want the `EnvTypes` alias to exist in the future (which was not sure at the time of creation). Also keep in mind that the proposed connectors API might change certain access patterns which makes me hesistant to actually declare certain parts as final.

**Comment by athei** [comment]
I agree. We can close this.
