### ISSUE TITLE
Question: Are there payable messages as in Solidity?

### ISSUE THREAD

**Issue by noahsalvadordenjo** [paritytech/ink#437]
Is there something like payable in solidity?

**Comment by Robbepop** [comment]
Currently ink! does not have syntax sugar for this use case.
However, you can easily mimic the behavior by adding the required conditional to your `non-payable` messages manually:
For example:
```rust
#[ink(message)]
fn transfer(&mut self, from: AccountId, to: AccountId, value: Balance) {
    assert!(self.env().transferred_balance() == 0, "cannot send balance to this message!");
    // do regular transfer procedure
}
```

In later ink! revisions we might think about adding syntactic sugar for this use case so that users might be able to flag messages or constructors using constructs such as:
```rust
#[ink(message)]
#[ink(payable)]
fn transfer(&mut self, from: AccountId, to: AccountId, value: Balance) {
    // do regular transfer procedure
}
```
or alternatively
```rust
#[ink(message, payable)]
fn transfer(&mut self, from: AccountId, to: AccountId, value: Balance) {
    // do regular transfer procedure
}
```

**Comment by Robbepop** [comment]
Payable messages have been added in ink! 3.0.
