### ISSUE TITLE
Generate Metadata doesn't seem to work and might be hard-coded

### ISSUE THREAD

**Issue by andysign** [paritytech/ink#444]
This is a bug concerning building of ink! smart contracts `generate-metadata`.

**Description of the bug**
A clear and concise description of what the bug or odd behavior is.

**Expected behavior**

**Screenshots**

**Additional context**

**FAQ**

Using `cargo contract --version`: 

```sh
$ cargo contract --version
cargo-contract 0.6.1
```

**Describe the bug**
Generate Metadata doesn't seem to work and might be hard-coded as it generates basically the same `metadata.json` file.

If I try:

```sh
cargo contract new flipper; cd flipper; cargo contract generate-metadata
```

the result is the same with

```sh
cargo contract new iterator; cd iterator; cargo contract generate-metadata
```

The only difference seems to be line `5`.

**Expected behavior**
It should generate a totally different json file for `Flipper`, `Iterator` etc.

**Screenshots**
This, I think will help explain the problem.

<img width="1651" alt="Screenshot 2020-06-11 at 02 36 21" src="https://user-images.githubusercontent.com/11134288/84335500-e5f48580-ab8c-11ea-9a25-9345be9b5097.png">

**Additional context**
When I upload the Wasm and the Json file I can't really interact with the samert contract instance for some reason and I don't know how to generate the Json file by hand.

**Comment by Robbepop** [comment]
The
```
cargo contract new flipper
```
command creates a new ink! smart contract that has the structure of a smart contract we call the Flipper smart contract.
The Flipper smart contract can be viewed as the "Hello, World!" of the smart contract world with the minimal API:
- `new`: To construct it given a start `bool` value.
- `flip`: To flip the `bool` value.
- `get`: To return the `bool` value.
So if you simply create 2 smart contracts with different names using the above command you will also receive very similar ink! metadata for both since they are structurally very similar. If you start to change the internals of your smart contracts you will see differences.

**Comment by dc-andysign** [comment]
> The
> 
> ```
> cargo contract new <contract_name>
> ```
> 
> command creates a new ink! smart contract that has the structure of a smart contract we call the Flipper smart contract.
> The Flipper smart contract can be viewed as the "Hello, World!" of the smart contract world with the minimal API:
> 
> * `new`: To construct it given a start `bool` value.
> * `flip`: To flip the `bool` value.
> * `get`: To return the `bool` value.
> 
> So if you simply create 2 smart contracts with different names using the above command you will also receive very similar ink! metadata for both since they are structurally very similar. If you start to change the internals of your smart contracts you will see differences.

in `Iterator` there are no bool variables... If I can find a guid how to create the metadata correctly manually I will do it...

**Comment by Robbepop** [comment]
The two commands
- `cargo contract new flipper`
- `cargo contract new iterator`
create basically the absolute same ink! smart contract twice with the only difference being the name. This is because we always generate the Flipper example contract as a template for users to have something to play around with upon `cargo contract new`.
That's why you see the same metadata being generated for both invocations.

The Flipper template smart contract has exactly one `bool` field which is exactly what you are seeing in the metadata. The generated metadata will change as soon as you actually adjust the generated ink! smart contracts.

**Comment by Robbepop** [comment]
Closing this issue since it seems to be resolved.

**Comment by andysign** [comment]
Strange, `cargo contract new erc20` outputs the same metadata json object.

**Comment by Robbepop** [comment]
> Strange, `cargo contract new erc20` outputs the same metadata json object.

I am very sorry to say that but my answer above really answered the "why" already and I cannot think of a better answer. Maybe others can.

If you want to dig more into smart contracts with ink! and `cargo-contract` you should go through our provided [ink! workshop](https://substrate.dev/substrate-contracts-workshop/#/) since it explains every step and each iteration in depth.

**Comment by riusricardo** [comment]
@andysign you should follow all the tutorial to get a better understanding of what is happening.
Another option is to can clone the ink! repo and build/generate-metadata directly on the erc20 example folder. If you build the code from this examples, you'll see that the metadata is different.
https://github.com/paritytech/ink/tree/master/examples/erc20

**Comment by andysign** [comment]
> @andysign you should follow all the tutorial to get a better understanding of what is happening.
> Another option is cloning the ink! repo and build/generate-metadata directly on the erc20 example folder. If you build the code from this examples, you'll see that the metadata is different.
> https://github.com/paritytech/ink/tree/master/examples/erc20

Yes, it works, thank you ! This is what I was talking about, the metadata json is completaly different now. I am sure I can upload the wasm bin and interact with it now properly :)
Thank you !
