### ISSUE TITLE
Storage layout description file generation

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#49]
It is possible to access (read) contract storage outside from contract execution.
This is especially useful since the current SRML contract module does not allow returning data to non-contract callers.
However, when using the pDSL the allocation of storage items is hidden behind abstractions and not very transparent to the outside.
To counteract this the `pdsl_lang` could generate a storage layout description file that users can use to know where they can access which data.

For a contract with a storage state like shown below a potential storage layout file could look like the following:

```rust
contract! {
    struct Vec2 {
        x: storage::Value<i32>,
        y: storage::Value<i32>,
    }
    ...
}
```

The storage layout description file:

```json
{
    "name": "Vec2",
    "fields": [
        {
            "name": "x",
            "key": 42
        },
        {
            "name": "y",
            "key": 1337
        }
    ]
}
```

Note that the above storage layout description file is just an example and doesn't demonstrate any true layout.

Also note that the above storage layout description file might be too simplified since we are interested in a very detailed look into the used data structures.
For example, describing a storage layout for a `storage::Value` requires just one `key` while describing a `storage::Vec` might require more and especially a key that is representing an entire array of elements.

In respect to the API description file we do not want to merge both files since they have a very different purpose and target very different clients.

# Complex Types

For more complex types such as `storage::Vec` that has a `len` and a `data` field we could do with a recursive design for fields like the below:

Example contract:

```rust
contract! {
    struct UserBase {
        users: storage::Vec<User>,
    }
    ...
}
```

Storage layout description file:

```json
{
    "name": "UserBase",
    "fields": [
        {
            "name": "users",
            "fields": [
                {
                    "name": "len",
                    "key": 1
                },
                {
                    "name": "data",
                    "key": 1000
                }
            ]
        }
    ]
}
```

Note that implementing this can quickly become tricky. We could introduce a new trait that the pDSL automatically and recursively (using `derive` macro) implements for all storage data structures and then pseudo-allocate these data structures during compilation of the contract while collecting their resulting keys. (Vague, needs more explanation!)

# Nested single-key structures

For single nested key structures, such as `storage::Value` itself that contains a single `storage::SyncCell` which itself contains a single `storage::TypedCell` etc. we want to flatten the layout structure. So instead of displaying a `storage::Value` as its exact internal representation, we directly use the common unique key as can be seen in the first example.

# Data Structure

The following simple data structure could work  as support for a simple and raw underlying implementation:

```rust
struct Key([u8; 32]);

struct Layout {
    name: String,
    layout: StorageLayout,
}

enum StorageLayout {
    Contiuous(ContiguousLayout),
    Group(GroupLayout),
}

struct ContiguousLayout {
    key: Key,
    amount: u32,
}

struct GroupLayout {
    group: Vec<Layout>,
}
```

**Comment by xlc** [comment]
I don't know pdsl well enough, but how is this different the metadata from substrate runtime?
Substrate metadata already descriptor the storage layout for runtime modules. Can we use the same format/implementation for contracts?

**Comment by pepyakin** [comment]
@xlc yeah, they are somewhat similar in what they are trying to achieve. However, there are some significant problems with doing what SRML is doing right now.

For one, SRML is really Rust biased. It uses Rust definitions, and the last time I checked, you could see something like `Default::default` as a initializer expression there : ). While personally I like Rust, I think it is important to give a way for other langauges. Not sure though if this issue is about this.

The second reason is that storage handling in SRML and pDSL differs from each other quite significantly and it feels like it is not feasible to try bridge the gap between them.

<hr>

Another, maybe a bit crazy way to solve the ABI interfacing issue, is to leverage webassembly blobs for describing storage layout. Here is the strawman description of the idea.

The blob could return a list of fields published by the contract, and the field can be either a value or a container. The host can request the blob to enumerate all values that are located in the container. The host can also request the blob to render a value. In the case of pDSL the blob can be generated from the definition of a contract.

This gives super wide range of possibilities for a target compiler since it is unconstrained on how to present its values. Such definition is Rust unbiased. 

However I can see the following downsides:

1. Such definition requires a wasm execution engine to extract the data. This is more or less OK for Web / JS applications of such data format, but maybe other applications might suffer.
2. This is a turing complete execution format. It can't mine dogecoins on a machine since it is useless (there are no ways for interaction with outside world, wasm is capability based), but it can fall into an endless loop. This might be not a big deal because it won't harm if the execution of that blob is terminated. Also in the case of block explorers the wasm blob are going to be produced by the trusted set of compilers anyway.
3. The format is a bit more bulkier. A dumb storage description would be more lightweight since the rendering capabilities are hardcoded in the host.

To mitigate the latter issue, we might want to introduce a hybrid approach where there are two parts in play. The consumer uses renderer (which is common for an entire language) and a dumb data descriptor. The renderer takes the data descriptor and parses it. This gives the same kind of flexibility, but makes renderer somewhat more trusted.

**Comment by xlc** [comment]
> For one, SRML is really Rust biased. It uses Rust definitions, and the last time I checked, you could see something like Default::default as a initializer expression there : ). While personally I like Rust, I think it is important to give a way for other langauges. Not sure though if this issue is about this.

`Default::default` was implementation flaw and it has been fixed. You can see the latest metadata here: https://github.com/polkadot-js/api/blob/master/packages/types/src/Metadata/v3/latest.substrate.v3.json#L9

While SRML is rust based,the metadata implementation have to be generalized to support SDK implementation in other languages. Otherwise it is a design flaw on SRML metadata and have to be fixed.

> The second reason is that storage handling in SRML and pDSL differs from each other quite significantly (and IMO discussion of that is out of scope for this issue) and it feels like it is not feasible to try bridge the gap between them.

I would like to know more about this on pDSL side. Any documents or which code I should read?

> Another, maybe a bit crazy way to solve the ABI interfacing issue, is to leverage webassembly blobs for describing storage layout.

Very similar to the Queries API you mentioned in the other substrate issue? Basically view function in Solidity right? But can may be able to run on client side?

----

To me, the SDK/apps can relays on a full node for communication, which then it can ask the full node to run some code to query some data (just like how current ethereum ecosystem).

Another way is the SDK relays on a light node (which can be embedded and running locally), which it then should either able to execute wasm, or execute some query language (the description file) to fetch the data (depends the definition and requirement of light node).

**Comment by pepyakin** [comment]
> Default::default was implementation flaw and it has been fixed. You can see the latest metadata here: https://github.com/polkadot-js/api/blob/master/packages/types/src/Metadata/v3/latest.substrate.v3.json#L9

Ah yeah, this looks better indeed. Although there are some rust-isms (i.e. generics, some types, tupels) left, e.g. `(BalanceOf,Vec<AccountId>)`.

> While SRML is rust based,the metadata implementation have to be generalized to support SDK implementation in other languages. Otherwise it is a design flaw on SRML metadata and have to be fixed.

That makes sense: plurality of languages for writing runtimes and sharing the common infrastructure sounds cool. Not sure if that was the original goal for SMLR though.

> I would like to know more about this on pDSL side. Any documents or which code I should read?

I'd guess that wiki and examples in this repo is all that we have. @Robbepop can correct me if I am wrong.

> Very similar to the Queries API you mentioned in the other substrate issue? Basically view function in Solidity right? But can may be able to run on client side?

There are a few similarities with [Queries API](https://github.com/paritytech/substrate/issues/2214#issuecomment-480217815), but I wouldn't say they are that similar. For example, Queries API are for querying some data by contracts and the code with that logic is the part of consensus (i.e. the result of a query influences the result of a contract execution). 

Here, in the first variation (where a blob is produced for each contract compilation), the code doesn't have anything to do with consensus. You can think of it as an adaptor between storage and some common interface, that can be used by frontend tools for generating user facing content or maybe by tools like debuggers. It theoretically could run on the client side as well (i.e. in the browser of the user), but that is complicated by the need to provide direct access to the storage to the client which might not be desirable or easy to implement.

And the way how the interfaces work is a bit different. In solidity view functions the interface is contract specific, that is contract defines whatever functions for accessing the storage it likes. The same (or really similar) goes for the Queries API, the module in question defines the view functions.

But in my idea all blobs follow the same common interface. All blobs compatible with that mechanism should implement all functions in this interface, and the purpose of this interface would be to provide an general introspection capability for some contract's storage.

**Comment by Robbepop** [comment]
Implemented by https://github.com/paritytech/ink/pull/104. Can be closed once merged.

**Comment by Robbepop** [comment]
Merged. Closed.
