### ISSUE TITLE
CI does not trigger a failure on TODO comments in UI tests

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#531]
I just discovered that we have a TODO comment in `master`: 
https://github.com/paritytech/ink/blob/master/crates/lang/macro/tests/ui/pass/05-erc721-contract.rs#L213.

The CI should cause a failed check when it finds a TODO/FIXME comment.

Our `.rustfmt.toml` already searches for those:
```
report_todo = "Always"
report_fixme = "Always"
```
But apparently it doesn't translate into a failed check.

**Comment by Robbepop** [comment]
I just see that this is inside a UI test. Maybe those are bit harder cases since they are packed behind the `trybuild` crate. Maybe `trybuild` must provide some features in order to check them? Is that even useful? Maybe we should just teach our CI to also check those UI tests in the future.

Thanks for the issue, anyways!
