### ISSUE TITLE
Examples cargo.toml bump to rc2 and crates.io dependancies?

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/ink#559]
Just wondering if it would be better for those interested in directly using the examples here to pull from crates.io vs an internal link to the files. I made the mistake of getting the raw cargo.toml files here and finding out the deps link internally to the repo. 

Would there be any reason _not_ to do this?

**Comment by Robbepop** [comment]
The problem with this is that if we would follow this suggestions then our examples would always be in sync with the latest released version and not in sync with our current main or `master` branch. That's why our examples directly link to crate in its own repo.

Maybe we should do a better job at telling people how to craft new contracts using `cargo contract new` instead.

**Comment by NukeManDan** [comment]
I think it would be in sync with what is published on crates.io / lib.rs - so this should be safe from unstable things on the master branch. I assume the version on package repos is only tagged release versions?

**Comment by Robbepop** [comment]
The examples are checked as part of the ink! CI for coverage of what they need from ink!. So they depending on `master` instead of some published version on crates.io is actually critical. Also it helps developers to easily test new features using the existing examples.
The way forward to create new contracts is always `cargo contract new` and that is our recommendation. We might need to communicate this better.
