### ISSUE TITLE
example delegator cannot be sign&submit into canvas

### ISSUE THREAD

**Issue by SeavantUUz** [paritytech/ink#646]
I tried to deploy example contract "delegator" into canvas-node though canvas-ui. The canvas-node is running in my local network.

Following Readme, using `./build-all.sh`, I got `delegator.contract`. As I tried to upload, it failed, told me "System.ExtrinsicFailed".

My canvas version: `canvas 0.1.0-258b0fa-x86_64-macos`, rustc version: `rustc 1.49.0-nightly (a1dfd2490 2020-10-05)`.

I fetched this from console.

```
signAndSend: status :: {"dispatchError":{"Other":null},"dispatchInfo":{"weight":1538411000,"class":"Normal","paysFee":"Yes"},"events":[{"phase":{"ApplyExtrinsic":1},"event":{"index":"0x0001","data":[{"Other":null},{"weight":1538411000,"class":"Normal","paysFee":"Yes"}]},"topics":[]}],"status":{"InBlock":"0x1b3be8ee3b84862dd2b929f437a3dc9889bf42b3ccc36c6f5a10e36cf75c1bbe"}}
```

hope it would be help !

Thx.

BTW, how could I get detail log about why did `System.ExtrinsicFailed` error happen.

**Comment by cmichi** [comment]
@SeavantUUz Thanks for the report. I'm closing this our issue has been fixed by now and [the `delegator` readme](https://github.com/paritytech/ink/tree/master/examples/delegator#delegator-smart-contract) has been updated.

>BTW, how could I get detail log about why did System.ExtrinsicFailed error happen.

There will be an event returned along the lines of `ExtrinsicFailed: OutOfGas`, in the `canvas-ui` this is visible as a notification after you've submitted the transaction.
