### ISSUE TITLE
Move high level storage APIs to contracts pallet

### ISSUE THREAD

**Issue by holygits** [paritytech/ink#687]
Wanted to open this as a dicussion topic.
It seems like contract wasm size is going to be significantly affected by the use of ink storage API boiler plate code.
Potentially many contracts will need to reuse this same code e.g. reading/writing to hash maps, sensibly allocating storage within address space etc.

Could consider moving things like map read/write into VM calls like `ext_read_map` / `ext_write_map`.
APIs like `ext_deposit_event` are nice high level APIs which make ink + contracts pallet a great combo imo

**Comment by HCastano** [comment]
@cmichi @athei Do you guys have any thoughts around this?

**Comment by athei** [comment]
Reading and writing hash maps **is** the API to the contracts pallet. It is a key value storage. I am strictly against offering anything that can be reasonably implemented in userspace (higher level data structures). Remember that we cannot change those interfaces. They need to be supported forever. Also this will be slow. Calling into the supervisor is costly. And don't forget that more API surface is more attack surface.

And for memory allocation: Yes, bringing its own allocator drives up the binary size. But I think this is just a lack of optimization. You could use much simpler allocators for contracts IMHO.

**Comment by Robbepop** [comment]
I agree with everything @athei just said and want to add that a more high-level read/write API as proposed by the issue's author is not really useful in ink!'s context also by a design perspective because it would mandate how all future smart contract languages will operate on their storage so it is especially important to provide low-level general and efficient primitives and let the languages take care of the user facing details.
