### ISSUE TITLE
New off-chain engine: Implement cross-contract methods

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#788]
Needed for https://github.com/paritytech/ink/issues/565.

- [ ] `call`
- [ ] `instantiate`

**Comment by Robbepop** [comment]
Indeed implementing this will be very difficult. I personally am out of ideas how to properly implement this given our current off-chain engine architectures. @cmichi do you have ideas?

@KaiserKarel What is your motivation to have this? Do you have some ideas in mind for the implementation?

**Comment by JayPavlina** [comment]
I need this to run tests that require cross contract calls. Unfortunately, most of my contracts use other contracts, usually ERC20 or ERC721, so I have to test with [redspot](https://github.com/patractlabs/redspot), which I find to be a huge drain on productivity. Being able to write all tests in rusts would be amazing. If this issue cannot be solved, I would love to know if there is some kind of workaround to be able to test contracts that call other contracts in rust.

**Comment by Robbepop** [comment]
> [...] Unfortunately, most of my contracts use other contracts [...]

Yep, this is kind of expected and normal with more complex smart contracts. The off-chain environments that have been implemented so far for ink! are limited to some extend. Also ink! generates very different code for both Wasm and off-chain compilation which was required to make limited off-chain testing simpler but which naturally makes it more difficult to emulate on-chain properly in an off-chain environment.
Given our limitations we already came quite a long way with the most recent off-chain environment implementation.

I don't think it is impossible to implement proper off-chain testing with cross-contract call support but it might eventually require a different architecture for our off-chain environments - not sure about this though.

The problem is that if you compile your smart contract for off-chain testing you do not compile it as a WebAssembly blob but instead as a standard Rust (x86 or so) library. If the contract is compiled with `ink-as-dependency` there no longer is a big difference when compiling for off-chain testing and we are able to directly include a depended-on contract into the root contract, so we actually are not using any external environment to do calls but use very efficient standard calling procedures. It is literally just incorporated into the root contract directly with all of its state instead of being put there as a direction via type-safe `AccountId` as it was the case as Wasm compilation.

**Comment by JayPavlina** [comment]
I had some success before when I compiled the dependency contract without the `ink-as-dependency` feature when I was testing, but I never found a setup that also allowed me to compile with `cargo contract`. Since features are additive, it's difficult to remove the `ink-as-dependency` feature only during testing.

**Comment by KaiserKarel** [comment]
> I need this to run tests that require cross contract calls.
Idem for me

**Comment by h4x3rotab** [comment]
I've implemented a PoV of macro based cross-contract mock demo in OpenBrush: https://github.com/Supercolony-net/openbrush-contracts/pull/136

**Comment by HCastano** [comment]
This was made irrelevant by the E2E testing framework introduced in ink! 4.0.
