### ISSUE TITLE
Account amounts not changing?

### ISSUE THREAD

**Issue by VadneyK** [paritytech/ink#817]
**Questions**
Hello I am [writing a smart contract](https://github.com/PlasmNetwork/dusty-faucet/tree/main/contract) very similar to the [contract-transfer in this repo here.](https://github.com/paritytech/ink/tree/master/examples/contract-transfer) I have locally tested and everything works fine, but when I deploy and interact with the smartcontract via polkadot network ui, the transactions say they have succeeded, but the actual amount of the tokens in the accounts are not changing and am very stuck. 

Here is more information:
https://github.com/polkadot-js/api/issues/3651#issuecomment-861727108

I also have a issue req on a seperate branch of the same repo to clear any confusions:
https://github.com/paritytech/ink/issues/816

What seems to be the issue with my fork of the [examples/contract-transfer](https://github.com/paritytech/ink/tree/master/examples/contract-transfer) ? not sure why this is happening.

**Comment by HCastano** [comment]
@VadneyK As I mentioned in https://github.com/polkadot-js/api/issues/3651 your transactions are not succeeding on chain. The contract is panicking somewhere, which is why `ContractTrapped` is being shown.

To figure out where you're going wrong I would make use of [`ink_env::debug_println!`](https://paritytech.github.io/ink/ink_env/macro.debug_println.html). You'll need to make sure the following are met, otherwise you won't print anything:
1. The `ink-debug` feature is enabled for `ink_env` in your contract's `Cargo.toml` (will require a recent version of `ink`)
2. You're using the latest version of the Canvas node
3. The calls you make are made over RPC (so not submitting the extrinsic on chain, I think that's the option name in Polkadot JS Apps)

**Comment by VadneyK** [comment]
@HCastano thanks! where can I view the outputs of the debug println?

**Comment by VadneyK** [comment]
![Screen Shot 2021-06-16 at 8 42 47 PM](https://user-images.githubusercontent.com/57117207/122327844-69a12a80-cee3-11eb-8c4b-2db1b4a165d8.png)
I just need to add this last line of code to enable debug right?

**Comment by VadneyK** [comment]
Wow I just found my issue. 1 default unit = 1 femto PLD = 10^-15 PLD... I just set amount = 10^16 PLD and it worked... damn lmao that took so long to figure out. Thanks for the help!

**Comment by VadneyK** [comment]
> @HCastano thanks! where can I view the outputs of the debug println?

@HCastano  Hey I still don't know how to view the errors, where can I view this? also how do I set the calls to be RPC rather than via extrinsics?

**Comment by HCastano** [comment]
> Hey I still don't know how to view the errors, where can I view this? 

You should see the errors in the logs of your Canvas dev node.

> also how do I set the calls to be RPC rather than via extrinsics?

There's an option in the UI before you fire off a transaction. 

<img width="284" alt="image" src="https://user-images.githubusercontent.com/12344623/122826603-59a59400-d2b1-11eb-96fc-76cfc099cfe8.png">

>  I just need to add this last line of code to enable debug right?

No, you need to do the following:

```toml
ink_env = { version = "3.0.0-rc3",  default-features = false, features = ["ink-debug"] }
```
