### ISSUE TITLE
About the design of payable

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/ink#877]
This syntax seems to be a direct reference to solidity? But I actually don't quite understand the meaning of such a design. In my opinion, it is more appropriate to divide into three values: must pay/must not pay/any
By the way, the check logic itself will slightly increase the wasm code size of ink because you have inlined it

**Comment by HCastano** [comment]
So I don't know about the history of it, but you can already achieve the three states you're interested in with the current language design.

```rust
#[ink(message, payable)]
pub fn must_pay(&self) {
  assert!(self.env().transferred_balance() > 0);
  ...
}

#[ink(message)]
pub fn must_not_pay(&self) {
  // No `payable` attribute, ink! will reject a fund transfer
  ...
}

#[ink(message, payable)]
pub fn any(&self) {
  ...
}
```

Do you have a pseudo-code proposal of what your solution would look like?

**Comment by yjhmelody** [comment]
I know it can be implemented in this way, but it is obviously unreasonable. Why does one of them require the user to implement the check manually, and the other two through annotations? And the front-end page/metadata.json does not express such semantics?

**Comment by cmichi** [comment]
So what you are missing to express is the difference between "must pay something" vs. "can pay something". We currently support only "can pay something" with `payable`.

The thing is that without further context "must pay something" doesn't offer that much more information, since it's still unclear how much payment is actually required. So you would still need the `assert!(self.env().transferred_balance() > 0);`, just with a specific number.

What we would gain though is to express the notion that a payment is required and UI's could e.g. display this requirement for a payment. 

An issue that I can think about is that having the semantic "must pay something" is not backwards compatible. If a contract is upgraded to e.g. a logic which then only requires payment in certain cases. UI's would then still have the metadata information that a payment is required. So in that way the current design allows for more flexibility and I can imagine that it would become a best practice to mark functions only as "can pay something" + an assertion to be more flexible for upgrades, opposed to marking them as "must pay".

Does anybody else have input on advantages/disadvantages of adding a "must pay" semantic?

**Comment by seanyoung** [comment]
I am fairly sure Solidity has an explicit payable option to prevent functions on contract from receiving value but then having no way of dealing with it; iow you might end up with value locked in a contract with no means of extracting it again, if value was sent by accident. This is why functions are by default non-payable.

An option "must pay" does not really serve much of a purpose; a function that must receive value should have some handling to ensure that the right amount was sent. It could be either too much or too little. I don't think a metadata for "must be non-zero" is particularly helpful, as this is just an edge case where any non-zero value will do. 

It might be more interesting to have a property "value-required" which is an rpc which returns the minimum/maximum value expected. Then again, making chain code larger for ui polish seems like a bad idea too.

**Comment by cmichi** [comment]
@yjhmelody I'm closing this issue, since this is what I feel the outcome of the above discussion is. To summarize the main reasons:
* We are currently of the opinion that a further distinction of "payable" into "must receive value" and "may receive value" doesn't provide that much more benefit, since it stays unclear how much value actually would be required for "must receive value".
* A further reason is that the check for this would require more code in ink! ‒ increasing the size of contracts. We feel that this outweighs the perceived benefits of a "must receive value" attribute.

**Comment by yjhmelody** [comment]
> A further reason is that the check for this would require more code in ink! ‒ increasing the size of contracts. We feel that this outweighs the perceived benefits of a "must receive value" attribute.

I think you are wrong, it can reduce the code size. If there is must pay semantics, then ink! does not need to automatically generate the check code `deny_payment`, because this check must be guaranteed by the developer, and this annotation also reminds the developer and user that the value of 0 should not be sent. For the front-end UI, refinement is more conducive to the user experience. For other languages, if they want to provide such semantics, it turns out that metadata.json is bound to ink! too tightly and can only continue to be compatible.

**Comment by seanyoung** [comment]
If a function is payable, i.e. "may receive value" then the deny_payment code is not needed either. Your proposed "must pay" increases the code size because a "deny_non_payment" code must be inserted.

**Comment by yjhmelody** [comment]
> If a function is payable, i.e. "may receive value" then the deny_payment code is not needed either. Your proposed "must pay" increases the code size because a "deny_non_payment" code must be inserted.

I said that the check should be guaranteed by the developer, so the logic of non-zero value check is not needed, which should reduce the code. Otherwise, Otherwise, isn’t it checked twice?
