### ISSUE TITLE
How to choose which Substrate version to target?

### ISSUE THREAD

**Issue by xlc** [paritytech/ink#95]
Substrate 1.0 and master are not compatible. What is the plan for ink to handle compatibility issues across different Substrate versions?

Many people are going to use ink with Substrate 1.0 and still some people will want to use against Substrate master.

One example of a contract API breaking change: https://github.com/paritytech/substrate/pull/2563
Not sure if this is the only one given that Substrate have no changelog to read.

**Comment by bkchr** [comment]
CC @Robbepop 

In general I would assume that `ink!` follows master. 1.0 is just a milestone. With 2.0 this will probably settle more, as 2.0 will/should be the basis of Polkadot 1.0.

**Comment by Robbepop** [comment]
This is a good question and we should definitely answer this soon in the official docs.
Since ink! is not a stable, nor a stabily released product it might break from time to time.
We also have not yet implemented proper solutions that would prevent the breakage for future updates to either Substrate or ink!, however, as soon as we stabilize ink! we will definitely do so; or even earlier than that.
Our current recommendation thus is currently to use the current `master` of Substrate together with ink!.

**Comment by Robbepop** [comment]
For a more elaborate answer go [here](https://github.com/paritytech/ink/issues/96#issuecomment-493389831).

**Comment by xlc** [comment]
Does ink aims to support multiple versions of substrate simultaneously? I have no idea how to achieve it but it seems important. Just like how iOS developer will want to ensure his app works with multiple versions of iOS.

**Comment by Robbepop** [comment]
Good question!
We could use some mechanism like this to specify a Substrate version for a concrete ink! smart contract:
https://github.com/paritytech/ink/issues/27
So the smart contract would be specified to work with exactly this version of Substrate.
However, the problem is that it is going to be hard to check the availability of the user's Substrate version.

The only sane thing we can do here is to not break things as soon as ink! stabilizes together with the version specifier that would always specify a certain major version of Substrate.

For example, if you specify `#[version = 1]` in your ink! smart contract you would be depending on Substrate version ^1.0 and the ink! and Substrate teams have to make sure that this is going to work.
This means that your smart contract is compatible with all Substrate versions of the v1.X series, e.g. v1.0, v1.1, etc.

**Comment by Robbepop** [comment]
I think for now it doesn't make sense to start supporting multiple different Substrate versions with ink! since everything in this ecosystem is still in heavy flux. Once Substrate and ink! development starts to stabilize notably we can think about this again.
Until then ink! is always targeting the latest working Substrate release.
